// ===== Utilities: i18n dictionary =====
const i18n = {
  fr: {
    site_title: "Lubérisse Badly | Portfolio",
    name: "Lubérisse Badly",
    tagline: "Spécialiste en Relations Internationales & Transition Écologique",
    nav_home: "Accueil",
    nav_education: "Formation",
    nav_experience: "Expériences",
    nav_skills: "Compétences",
    nav_contact: "Contact",
    hero_title: "Construire des passerelles entre les peuples et la planète",
    hero_desc: "Professionnel dynamique, organisé et résilient. Master 2 en Relations Internationales, Licence en Droit, et solide expérience juridique, administrative et diplomatique. Spécialisé en transition écologique, gestion de projets et communication interculturelle.",
    btn_download: "Télécharger le CV (PDF)",
    btn_contact: "Me contacter",
    education_title: "Formation",
    edu_m2_title: "Master 2 – Relations Internationales & Transition Écologique",
    edu_m2_dates: "2022–2024",
    edu_m2_b1: "Analyse des dynamiques internationales",
    edu_m2_b2: "Gestion de projets & acteurs locaux",
    edu_m2_b3: "Communication et négociation interculturelle",
    edu_llb_title: "Licence en Droit",
    edu_llb_dates: "2015–2019",
    edu_llb_b1: "Droit civil & pénal haïtien",
    edu_llb_b2: "Interprétation de textes juridiques",
    edu_llb_b3: "Rédaction d'actes juridiques",
    edu_acc_title: "Attestation de Licence en Comptabilité",
    edu_acc_dates: "2001–2008",
    edu_acc_b1: "Principes comptables",
    edu_acc_b2: "Analyses financières & gestion de projets",
    exp_title: "Expériences",
    exp_c_meci_title: "Responsable juridique & partenariats",
    exp_c_meci_dates: "Depuis 2024",
    exp_c_meci_b1: "Pilotage juridique, conventions & partenariats",
    exp_c_meci_b2: "Appui à la stratégie climat Caraïbes–Amérique du Nord",
    exp_consulat_title: "Stagiaire – Consulat Général d’Haïti",
    exp_consulat_dates: "Sept.–Déc. 2024",
    exp_consulat_b1: "Accueil, information & orientation des usagers",
    exp_consulat_b2: "Rédaction de notes & rapports consulaires",
    exp_consulat_b3: "Veille informationnelle",
    exp_minabi_title: "Stagiaire – Association MINABI",
    exp_minabi_dates: "Avr.–Juil. 2024",
    exp_minabi_b1: "Gestion de projets & conduite de réunions",
    exp_minabi_b2: "Rédaction de rapports & fiches de synthèse",
    exp_sncfl_title: "Hôte d’accueil – City One / SNCF",
    exp_sncfl_dates: "Août–Déc. 2023",
    exp_sncfl_b1: "Orientation des clients & assistance billetterie",
    exp_sncfl_b2: "Rapports opérationnels",
    exp_acropole_title: "Avocat Assistant – L’Acropole",
    exp_acropole_dates: "2019–2022",
    exp_acropole_b1: "Rédaction d’actes & gestion des dossiers",
    exp_acropole_b2: "Représentation conjointe des clients",
    exp_pnh_title: "Chef d’alerte – Police Nationale d’Haïti (DCPJ)",
    exp_pnh_dates: "2006–2022",
    exp_pnh_b1: "Coordination d’équipes & gestion de crises",
    exp_pnh_b2: "Analyse d’incidents & rapports de synthèse",
    skills_title: "Compétences & Langues",
    skills_core_title: "Compétences clés",
    skill_ri: "Relations internationales",
    skill_franco: "Francophonie",
    skill_ecotrans: "Transition écologique",
    skill_proj: "Gestion de projets & crises",
    skill_comm: "Communication interculturelle",
    skill_lead: "Leadership & coordination",
    skill_office: "Word · Excel · PowerPoint",
    skills_lang_title: "Langues",
    lang_fr_label: "Français",
    lang_fr_val: "Langue maternelle",
    lang_en_label: "Anglais",
    lang_en_val: "B2",
    lang_es_label: "Espagnol",
    lang_es_val: "B1",
    contact_title: "Contact",
    contact_loc: "Verneuil‑sur‑Seine (78480), Île‑de‑France",
    contact_permis: "Permis B",
    contact_cv_title: "Télécharger le CV",
    btn_download_2: "Télécharger le CV (PDF)",
    contact_msg_label: "Un message rapide ?",
    contact_msg_ph: "Bonjour...",
    contact_btn_send: "Envoyer par email",
    footer_all: "Tous droits réservés"
  },
  en: {
    site_title: "Lubérisse Badly | Portfolio",
    name: "Lubérisse Badly",
    tagline: "International Relations & Green Transition Specialist",
    nav_home: "Home",
    nav_education: "Education",
    nav_experience: "Experience",
    nav_skills: "Skills",
    nav_contact: "Contact",
    hero_title: "Bridging people and the planet",
    hero_desc: "Dynamic, organized and resilient professional. Master’s in International Relations, Law degree, and strong legal, administrative and diplomatic experience. Specialized in green transition, project management and cross‑cultural communication.",
    btn_download: "Download CV (PDF)",
    btn_contact: "Contact me",
    education_title: "Education",
    edu_m2_title: "Master’s – International Relations & Green Transition",
    edu_m2_dates: "2022–2024",
    edu_m2_b1: "Analysis of international dynamics",
    edu_m2_b2: "Project management & local stakeholders",
    edu_m2_b3: "Intercultural communication & negotiation",
    edu_llb_title: "Bachelor’s in Law",
    edu_llb_dates: "2015–2019",
    edu_llb_b1: "Haitian civil & criminal law",
    edu_llb_b2: "Legal text interpretation",
    edu_llb_b3: "Drafting legal documents",
    edu_acc_title: "Accounting (certificate/attestation)",
    edu_acc_dates: "2001–2008",
    edu_acc_b1: "Accounting principles",
    edu_acc_b2: "Financial analysis & project management",
    exp_title: "Experience",
    exp_c_meci_title: "Legal & Partnerships Lead",
    exp_c_meci_dates: "Since 2024",
    exp_c_meci_b1: "Legal oversight, agreements & partnerships",
    exp_c_meci_b2: "Support for climate strategy Caribbean–North America",
    exp_consulat_title: "Intern – Consulate General of Haiti",
    exp_consulat_dates: "Sep–Dec 2024",
    exp_consulat_b1: "Front‑desk, guidance & user support",
    exp_consulat_b2: "Drafting notes & consular reports",
    exp_consulat_b3: "Information monitoring",
    exp_minabi_title: "Intern – MINABI Association",
    exp_minabi_dates: "Apr–Jul 2024",
    exp_minabi_b1: "Project management & meeting facilitation",
    exp_minabi_b2: "Detailed reports & briefing notes",
    exp_sncfl_title: "Host – City One / SNCF",
    exp_sncfl_dates: "Aug–Dec 2023",
    exp_sncfl_b1: "Customer orientation & ticketing assistance",
    exp_sncfl_b2: "Operational reporting",
    exp_acropole_title: "Assistant Lawyer – L’Acropole",
    exp_acropole_dates: "2019–2022",
    exp_acropole_b1: "Drafting legal acts & case management",
    exp_acropole_b2: "Joint client representation",
    exp_pnh_title: "Alert Chief – Haitian National Police (DCPJ)",
    exp_pnh_dates: "2006–2022",
    exp_pnh_b1: "Team coordination & crisis management",
    exp_pnh_b2: "Incident analysis & synthesis reports",
    skills_title: "Skills & Languages",
    skills_core_title: "Core skills",
    skill_ri: "International relations",
    skill_franco: "Francophonie",
    skill_ecotrans: "Green transition",
    skill_proj: "Project & crisis management",
    skill_comm: "Cross‑cultural communication",
    skill_lead: "Leadership & coordination",
    skill_office: "Word · Excel · PowerPoint",
    skills_lang_title: "Languages",
    lang_fr_label: "French",
    lang_fr_val: "Native",
    lang_en_label: "English",
    lang_en_val: "B2",
    lang_es_label: "Spanish",
    lang_es_val: "B1",
    contact_title: "Contact",
    contact_loc: "Verneuil‑sur‑Seine (78480), Île‑de‑France",
    contact_permis: "Driving License B",
    contact_cv_title: "Download CV",
    btn_download_2: "Download CV (PDF)",
    contact_msg_label: "Quick message?",
    contact_msg_ph: "Hello...",
    contact_btn_send: "Send by email",
    footer_all: "All rights reserved"
  },
  es: {
    site_title: "Lubérisse Badly | Portafolio",
    name: "Lubérisse Badly",
    tagline: "Especialista en Relaciones Internacionales y Transición Ecológica",
    nav_home: "Inicio",
    nav_education: "Formación",
    nav_experience: "Experiencia",
    nav_skills: "Habilidades",
    nav_contact: "Contacto",
    hero_title: "Tendiendo puentes entre la gente y el planeta",
    hero_desc: "Profesional dinámico, organizado y resiliente. Máster en Relaciones Internacionales, licenciatura en Derecho y sólida experiencia jurídica, administrativa y diplomática. Especializado en transición ecológica, gestión de proyectos y comunicación intercultural.",
    btn_download: "Descargar CV (PDF)",
    btn_contact: "Contáctame",
    education_title: "Formación",
    edu_m2_title: "Máster – Relaciones Internacionales y Transición Ecológica",
    edu_m2_dates: "2022–2024",
    edu_m2_b1: "Análisis de dinámicas internacionales",
    edu_m2_b2: "Gestión de proyectos y actores locales",
    edu_m2_b3: "Comunicación y negociación intercultural",
    edu_llb_title: "Licenciatura en Derecho",
    edu_llb_dates: "2015–2019",
    edu_llb_b1: "Derecho civil y penal haitiano",
    edu_llb_b2: "Interpretación de textos jurídicos",
    edu_llb_b3: "Redacción de documentos legales",
    edu_acc_title: "Contabilidad (certificado)",
    edu_acc_dates: "2001–2008",
    edu_acc_b1: "Principios contables",
    edu_acc_b2: "Análisis financiero y gestión de proyectos",
    exp_title: "Experiencia",
    exp_c_meci_title: "Responsable jurídico y alianzas",
    exp_c_meci_dates: "Desde 2024",
    exp_c_meci_b1: "Supervisión legal, convenios y alianzas",
    exp_c_meci_b2: "Apoyo a la estrategia climática Caribe–Norteamérica",
    exp_consulat_title: "Practicante – Consulado General de Haití",
    exp_consulat_dates: "Sep–Dic 2024",
    exp_consulat_b1: "Atención, información y orientación a usuarios",
    exp_consulat_b2: "Redacción de notas e informes consulares",
    exp_consulat_b3: "Vigilancia informativa",
    exp_minabi_title: "Practicante – Asociación MINABI",
    exp_minabi_dates: "Abr–Jul 2024",
    exp_minabi_b1: "Gestión de proyectos y conducción de reuniones",
    exp_minabi_b2: "Informes detallados y fichas de síntesis",
    exp_sncfl_title: "Anfitrión – City One / SNCF",
    exp_sncfl_dates: "Ago–Dic 2023",
    exp_sncfl_b1: "Orientación al cliente y asistencia de boletos",
    exp_sncfl_b2: "Reportes operativos",
    exp_acropole_title: "Asistente de abogado – L’Acropole",
    exp_acropole_dates: "2019–2022",
    exp_acropole_b1: "Redacción de actos y gestión de expedientes",
    exp_acropole_b2: "Representación conjunta de clientes",
    exp_pnh_title: "Jefe de alerta – Policía Nacional de Haití (DCPJ)",
    exp_pnh_dates: "2006–2022",
    exp_pnh_b1: "Coordinación de equipos y gestión de crisis",
    exp_pnh_b2: "Análisis de incidentes e informes de síntesis",
    skills_title: "Habilidades e Idiomas",
    skills_core_title: "Habilidades clave",
    skill_ri: "Relaciones internacionales",
    skill_franco: "Francofonía",
    skill_ecotrans: "Transición ecológica",
    skill_proj: "Gestión de proyectos y crisis",
    skill_comm: "Comunicación intercultural",
    skill_lead: "Liderazgo y coordinación",
    skill_office: "Word · Excel · PowerPoint",
    skills_lang_title: "Idiomas",
    lang_fr_label: "Francés",
    lang_fr_val: "Nativo",
    lang_en_label: "Inglés",
    lang_en_val: "B2",
    lang_es_label: "Español",
    lang_es_val: "B1",
    contact_title: "Contacto",
    contact_loc: "Verneuil‑sur‑Seine (78480), Île‑de‑France",
    contact_permis: "Permiso B",
    contact_cv_title: "Descargar CV",
    btn_download_2: "Descargar CV (PDF)",
    contact_msg_label: "¿Mensaje rápido?",
    contact_msg_ph: "Hola...",
    contact_btn_send: "Enviar por correo",
    footer_all: "Todos los derechos reservados"
  },
  pt: {
    site_title: "Lubérisse Badly | Portfólio",
    name: "Lubérisse Badly",
    tagline: "Especialista em Relações Internacionais e Transição Ecológica",
    nav_home: "Início",
    nav_education: "Formação",
    nav_experience: "Experiência",
    nav_skills: "Competências",
    nav_contact: "Contato",
    hero_title: "Ligando pessoas e o planeta",
    hero_desc: "Profissional dinâmico, organizado e resiliente. Mestrado em Relações Internacionais, bacharelado em Direito e sólida experiência jurídica, administrativa e diplomática. Especializado em transição ecológica, gestão de projetos e comunicação intercultural.",
    btn_download: "Baixar CV (PDF)",
    btn_contact: "Entrar em contato",
    education_title: "Formação",
    edu_m2_title: "Mestrado – Relações Internacionais e Transição Ecológica",
    edu_m2_dates: "2022–2024",
    edu_m2_b1: "Análise das dinâmicas internacionais",
    edu_m2_b2: "Gestão de projetos e atores locais",
    edu_m2_b3: "Comunicação e negociação intercultural",
    edu_llb_title: "Bacharelado em Direito",
    edu_llb_dates: "2015–2019",
    edu_llb_b1: "Direito civil e penal haitiano",
    edu_llb_b2: "Interpretação de textos jurídicos",
    edu_llb_b3: "Redação de documentos jurídicos",
    edu_acc_title: "Contabilidade (certificado)",
    edu_acc_dates: "2001–2008",
    edu_acc_b1: "Princípios contábeis",
    edu_acc_b2: "Análises financeiras e gestão de projetos",
    exp_title: "Experiência",
    exp_c_meci_title: "Líder Jurídico e Parcerias",
    exp_c_meci_dates: "Desde 2024",
    exp_c_meci_b1: "Supervisão jurídica, acordos e parcerias",
    exp_c_meci_b2: "Apoio à estratégia climática Caribe–América do Norte",
    exp_consulat_title: "Estagiário – Consulado Geral do Haiti",
    exp_consulat_dates: "Set–Dez 2024",
    exp_consulat_b1: "Atendimento, informação e orientação a usuários",
    exp_consulat_b2: "Redação de notas e relatórios consulares",
    exp_consulat_b3: "Monitoramento de informações",
    exp_minabi_title: "Estagiário – Associação MINABI",
    exp_minabi_dates: "Abr–Jul 2024",
    exp_minabi_b1: "Gestão de projetos e condução de reuniões",
    exp_minabi_b2: "Relatórios detalhados e notas de síntese",
    exp_sncfl_title: "Recepcionista – City One / SNCF",
    exp_sncfl_dates: "Ago–Dez 2023",
    exp_sncfl_b1: "Orientação ao cliente e assistência de bilhetes",
    exp_sncfl_b2: "Relatórios operacionais",
    exp_acropole_title: "Assistente de Advogado – L’Acropole",
    exp_acropole_dates: "2019–2022",
    exp_acropole_b1: "Redação de atos e gestão de processos",
    exp_acropole_b2: "Representação conjunta de clientes",
    exp_pnh_title: "Chefe de Alerta – Polícia Nacional do Haiti (DCPJ)",
    exp_pnh_dates: "2006–2022",
    exp_pnh_b1: "Coordenação de equipes e gestão de crises",
    exp_pnh_b2: "Análise de incidentes e relatórios de síntese",
    skills_title: "Competências e Idiomas",
    skills_core_title: "Competências‑chave",
    skill_ri: "Relações internacionais",
    skill_franco: "Francofonia",
    skill_ecotrans: "Transição ecológica",
    skill_proj: "Gestão de projetos e crises",
    skill_comm: "Comunicação intercultural",
    skill_lead: "Liderança e coordenação",
    skill_office: "Word · Excel · PowerPoint",
    skills_lang_title: "Idiomas",
    lang_fr_label: "Francês",
    lang_fr_val: "Nativo",
    lang_en_label: "Inglês",
    lang_en_val: "B2",
    lang_es_label: "Espanhol",
    lang_es_val: "B1",
    contact_title: "Contato",
    contact_loc: "Verneuil‑sur‑Seine (78480), Île‑de‑France",
    contact_permis: "Carta B",
    contact_cv_title: "Baixar CV",
    btn_download_2: "Baixar CV (PDF)",
    contact_msg_label: "Mensagem rápida?",
    contact_msg_ph: "Olá...",
    contact_btn_send: "Enviar por e‑mail",
    footer_all: "Todos os direitos reservados"
  }
};

// ===== Language switcher =====
const select = document.getElementById('lang');
const htmlEl = document.documentElement;
const savedLang = localStorage.getItem('lang') || 'fr';
select.value = savedLang;
applyLang(savedLang);

select.addEventListener('change', (e)=>{
  const lang = e.target.value;
  localStorage.setItem('lang', lang);
  applyLang(lang);
});

function applyLang(lang){
  const dict = i18n[lang] || i18n.fr;
  document.title = dict.site_title;
  // elements with data-i18n replace innerText
  document.querySelectorAll('[data-i18n]').forEach(el=>{
    const key = el.getAttribute('data-i18n');
    if(dict[key]) el.textContent = dict[key];
  });
  // placeholders
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{
    const key = el.getAttribute('data-i18n-placeholder');
    if(dict[key]) el.setAttribute('placeholder', dict[key]);
  });
}

// ===== Theme toggle =====
const themeToggle = document.getElementById('themeToggle');
const savedTheme = localStorage.getItem('theme') || 'dark';
if(savedTheme === 'light'){ document.body.classList.add('light'); }
themeToggle.addEventListener('click', ()=>{
  document.body.classList.toggle('light');
  localStorage.setItem('theme', document.body.classList.contains('light') ? 'light' : 'dark');
});

// ===== Reveal on scroll (2D animation) =====
const observer = new IntersectionObserver((entries)=>{
  entries.forEach(entry=>{
    if(entry.isIntersecting){
      entry.target.classList.add('visible');
      observer.unobserve(entry.target);
    }
  });
},{ threshold: 0.15 });
document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));

// ===== Year =====
document.getElementById('year').textContent = new Date().getFullYear();

// ===== Smooth scroll for internal links =====
document.querySelectorAll('a[href^="#"]').forEach(a=>{
  a.addEventListener('click', (e)=>{
    const id = a.getAttribute('href').slice(1);
    const target = document.getElementById(id);
    if(target){
      e.preventDefault();
      window.scrollTo({ top: target.offsetTop - 90, behavior: 'smooth' });
    }
  });
});
